#!/usr/bin/env python3
"""Grok Build config helper for the Kiro gateway.

Thin client: it speaks HTTP to the gateway's own
``GET /integrations/grok-build.toml`` endpoint and edits ``~/.grok/config.toml``.
It contains no auth, token-refresh, region, header or catalog logic — the gateway
is the single source of truth for all of that.

Subcommands
-----------
setup    fetch the live document and merge our sections into your config
doctor   diff your config against the live document and report drift only
update   refresh the managed model tables in place

Exit codes
----------
0  healthy / nothing to change
1  drift found or changes pending (dry run)
2  usage error, connection failure, bad key, malformed response

Why the merge is text-based
---------------------------
The stdlib has a TOML *reader* (``tomllib``) but no writer. Round-tripping the whole
document through a parser and re-emitting it would silently destroy comments, blank
lines and key order — and ``~/.grok/config.toml`` legitimately holds unrelated state
such as ``[cli] installer = "npm"``, which the npm-managed updater depends on. So this
helper edits the file *as text*: it drops only the table blocks it owns
(``[endpoints]``, ``[models]``, ``[model.*]``) and appends freshly generated ones,
leaving every other byte untouched. ``tomllib`` is used for reading, validation and
comparison only.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import difflib
import os
import re
import shutil
import sys
import tempfile
import tomllib
import urllib.error
import urllib.parse
import urllib.request

EXIT_OK = 0
EXIT_DRIFT = 1
EXIT_ERROR = 2

DEFAULT_URL = "http://localhost:8000"
DEFAULT_CONFIG = "~/.grok/config.toml"
DEFAULT_ENV_KEY = "KIRO_GATEWAY_KEY"
EXPECTED_BACKEND = "chat_completions"
REDACTED = "<redacted>"

# Table paths whose first segment is one of these are generated by us and are the only
# thing setup/update may replace.
OWNED_ROOTS = frozenset({"endpoints", "models", "model"})

# A plausible environment-variable NAME, which is all we ever store.
_ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_SECRETISH_LINE_RE = re.compile(r"^(\s*)(api_key|env_key)(\s*=\s*)(.+)$")


class HelperError(Exception):
    """Any expected, user-facing failure. Never surfaces as a traceback."""


# --------------------------------------------------------------------------- #
# fetching
# --------------------------------------------------------------------------- #
def fetch_document(
    url: str,
    api_key: str | None,
    base_url: str | None = None,
    env_key: str | None = None,
    timeout: float = 30.0,
) -> str:
    """GET the gateway's Grok Build document as text. Raises HelperError on failure."""
    params: dict[str, str] = {}
    if base_url:
        params["base_url"] = base_url
    if env_key:
        params["env_key"] = env_key

    endpoint = url.rstrip("/") + "/integrations/grok-build.toml"
    full = endpoint + ("?" + urllib.parse.urlencode(params) if params else "")

    request = urllib.request.Request(full, method="GET")
    if api_key:
        request.add_header("Authorization", f"Bearer {api_key}")
        request.add_header("x-api-key", api_key)

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            raw = response.read()
    except urllib.error.HTTPError as exc:
        if exc.code in (401, 403):
            raise HelperError(
                f"Gateway rejected the API key ({exc.code}). Pass --api-key or set "
                "KIRO_GATEWAY_KEY to the gateway's proxy API key."
            ) from None
        if exc.code == 404:
            raise HelperError(
                f"{endpoint} returned 404 — this gateway is too old to expose the "
                "Grok Build integration endpoint."
            ) from None
        raise HelperError(f"Gateway returned HTTP {exc.code} for {endpoint}.") from None
    except urllib.error.URLError as exc:
        raise HelperError(
            f"Could not reach the gateway at {url} ({exc.reason}). Is it running, "
            "and is --url correct?"
        ) from None
    except TimeoutError:
        raise HelperError(f"Timed out talking to the gateway at {url}.") from None

    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        raise HelperError(
            f"Gateway response from {endpoint} was not valid UTF-8."
        ) from None

    document = parse_toml(text, f"gateway response from {endpoint}")
    if "endpoints" not in document:
        raise HelperError(
            "Gateway response has no [endpoints] table — unexpected document shape. "
            "Check that --url points at the gateway and not at a proxy or login page."
        )
    return text


# --------------------------------------------------------------------------- #
# local config I/O
# --------------------------------------------------------------------------- #
def config_path(raw: str | None) -> str:
    return os.path.abspath(os.path.expanduser(raw or DEFAULT_CONFIG))


def parse_toml(text: str, label: str) -> dict:
    """tomllib parse with a clean, actionable message instead of a traceback."""
    try:
        return tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise HelperError(f"{label} is not valid TOML: {exc}") from None


def load_text(path: str) -> str:
    if not os.path.exists(path):
        return ""
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    except OSError as exc:
        raise HelperError(f"Could not read {path}: {exc.strerror}.") from None
    except UnicodeDecodeError:
        raise HelperError(f"{path} is not valid UTF-8 text.") from None


def write_text(path: str, text: str) -> str | None:
    """Back up any existing file, then write atomically. Returns the backup path."""
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)

    backup = None
    if os.path.exists(path):
        stamp = _dt.datetime.now().strftime("%Y%m%d-%H%M%S")
        backup = f"{path}.bak-{stamp}"
        shutil.copy2(path, backup)

    handle = tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=directory, prefix=".grok-config-", suffix=".tmp",
        delete=False,
    )
    try:
        with handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(handle.name, path)
    except BaseException:
        # The original file is still intact: nothing was written in place.
        try:
            os.unlink(handle.name)
        except OSError:
            pass
        raise
    return backup


# --------------------------------------------------------------------------- #
# text-level table surgery
# --------------------------------------------------------------------------- #
def _split_segments(path_text: str) -> list[str]:
    """Split a table path on unquoted dots: model."a.b" -> ['model', 'a.b']."""
    segments: list[str] = []
    current = ""
    quote = None
    for char in path_text:
        if quote:
            current += char
            if char == quote:
                quote = None
            continue
        if char in "\"'":
            quote = char
            current += char
            continue
        if char == ".":
            segments.append(current)
            current = ""
            continue
        current += char
    segments.append(current)
    return [s.strip().strip("\"'") for s in segments]


def _header_segments(line: str) -> list[str] | None:
    """Return the table path of a `[table]` / `[[array]]` header line, else None."""
    stripped = line.strip()
    if not stripped.startswith("[") or not stripped.endswith("]"):
        return None
    inner = stripped[2:-2] if stripped.startswith("[[") else stripped[1:-1]
    if not inner.strip():
        return None
    return _split_segments(inner)


def split_blocks(text: str) -> list[tuple[list[str] | None, str]]:
    """
    Split TOML text into (table_path_or_None, raw_text) blocks.

    The run of comment/blank lines immediately above a header is attached to that
    header's block, because a comment written there documents the table below it — that
    is what lets our own generated banner be replaced instead of duplicated on every
    re-run. Comments that follow a key stay with the table they are in. The first block
    (path None) is the pre-table preamble.
    """
    blocks: list[tuple[list[str] | None, str]] = []
    current_path: list[str] | None = None
    current: list[str] = []
    for line in text.splitlines(keepends=True):
        segments = _header_segments(line)
        if segments is not None:
            # Hand back any comment/blank tail to the table it introduces.
            tail: list[str] = []
            while current and (not current[-1].strip() or current[-1].lstrip().startswith("#")):
                tail.insert(0, current.pop())
            if current:
                blocks.append((current_path, "".join(current)))
            current_path = segments
            current = tail + [line]
        else:
            current.append(line)
    if current:
        blocks.append((current_path, "".join(current)))
    return blocks


def is_owned(path: list[str] | None) -> bool:
    return bool(path) and path[0] in OWNED_ROOTS


def merge_document(existing_text: str, document: str) -> str:
    """
    Replace only our own tables, preserving every other byte of the user's file.

    Unrelated tables ([cli], [mcp_servers], [ui], ...), the preamble, comments, blank
    lines and key order are all carried through verbatim; our generated sections are
    appended at the end. Re-running is idempotent.
    """
    kept = [
        raw for path, raw in split_blocks(existing_text) if not is_owned(path)
    ]
    preserved = "".join(kept)
    body = document if document.endswith("\n") else document + "\n"
    if not preserved.strip():
        return body
    return preserved.rstrip("\n") + "\n\n" + body


# --------------------------------------------------------------------------- #
# secret hygiene
# --------------------------------------------------------------------------- #
def looks_like_env_name(value: object) -> bool:
    return isinstance(value, str) and bool(_ENV_NAME_RE.match(value.strip()))


def redact_text(text: str) -> str:
    """Replace any api_key/env_key value that is not a plain env-var NAME."""
    out = []
    for line in text.splitlines():
        match = _SECRETISH_LINE_RE.match(line)
        if match:
            indent, key, sep, value = match.groups()
            literal = value.strip().strip('"').strip("'")
            if key == "api_key" or not looks_like_env_name(literal):
                line = f"{indent}{key}{sep}{REDACTED}"
        out.append(line)
    return "\n".join(out)


def render_diff(before: str, after: str, path: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            redact_text(before).splitlines(),
            redact_text(after).splitlines(),
            fromfile=f"{path} (current)",
            tofile=f"{path} (proposed)",
            lineterm="",
        )
    )


# --------------------------------------------------------------------------- #
# doctor
# --------------------------------------------------------------------------- #
def _models_of(document: dict) -> dict:
    tables = document.get("model")
    return tables if isinstance(tables, dict) else {}


# Auxiliary roles in [models]. Unset, Grok resolves them against its own built-in xAI
# model — observed as `aux_model=grok-4.6`, which this gateway rejects with
# INVALID_MODEL_ID, so every session emitted one doomed request and session titles fell
# back to truncated user text. image_description is optional: the gateway omits it when
# no visible model accepts image input, and a missing key is better than a wrong one.
AUX_ROLES = ("session_summary", "web_search", "prompt_suggestions")
OPTIONAL_ROLES = ("image_description",)

# Grok authenticates the MODEL-LIST fetch (GET {base_url}/models) with XAI_API_KEY
# specifically; the per-model `env_key` only covers INFERENCE. Measured: without
# XAI_API_KEY every `grok` invocation produced 2x `GET /v1/models` 401 and Grok silently
# fell back to whatever [model.*] tables happened to be in the file; with it set, 0x 401
# and 1x 200. So the file can be perfectly correct and discovery still be broken.
MODEL_LIST_ENV_VAR = "XAI_API_KEY"

_XAI_EXPLANATION = (
    f"{MODEL_LIST_ENV_VAR} is not set in this environment. Grok authenticates its "
    f"model-list fetch ({{base_url}}/models) with {MODEL_LIST_ENV_VAR} specifically — "
    "the per-model env_key only covers inference — so discovery fails silently (401) "
    "and Grok falls back to whatever [model.*] tables happen to be in this file. "
    f"Export {MODEL_LIST_ENV_VAR} with the same gateway key."
)

_AUX_EXPLANATION = (
    "Grok would fall back to its built-in xAI model for this role, and every session "
    "would emit a request this gateway rejects."
)


def _diagnose_roles(local: dict, live_models: dict) -> list[str]:
    """Check that each [models] role names a model this gateway actually serves."""
    findings: list[str] = []
    models = local.get("models")
    if not isinstance(models, dict):
        models = {}

    for role in AUX_ROLES:
        value = models.get(role)
        if value is None:
            findings.append(
                f"[models] {role} is not set — run 'setup'. {_AUX_EXPLANATION}"
            )
        elif live_models and value not in live_models:
            findings.append(
                f"[models] {role} names '{value}', which is not available upstream. "
                f"{_AUX_EXPLANATION}"
            )

    for role in OPTIONAL_ROLES:
        value = models.get(role)
        if value is not None and live_models and value not in live_models:
            findings.append(
                f"[models] {role} names '{value}', which is not available upstream. "
                f"{_AUX_EXPLANATION}"
            )

    return findings


def diagnose_environment(local: dict, environ=None) -> list[str]:
    """
    Report environment-level drift. The config file can be byte-perfect and Grok still
    fail because the key is absent from the interactive shell — the real user-reported
    failure mode: Grok fell back to grok.com session auth and sent its own xAI token to
    the gateway, which rejected all inference with 401.

    Presence is checked with `in os.environ` only. No value is ever read, compared,
    printed or echoed — findings name the VARIABLE only.
    """
    env = os.environ if environ is None else environ
    findings: list[str] = []

    names: list[str] = []
    for model_id, table in sorted(_models_of(local).items()):
        if not isinstance(table, dict):
            continue
        env_key = table.get("env_key")
        if isinstance(env_key, str) and looks_like_env_name(env_key):
            name = env_key.strip()
            if name not in names:
                names.append(name)

    for name in names:
        if name not in env:
            findings.append(
                f"environment variable {name} (named by [model.*] env_key) is not set "
                "in this environment, so Grok cannot authenticate to this gateway. It "
                "would fall back to its grok.com login session and send an xAI token, "
                f"which this gateway rejects with 401. Export {name} in the shell that "
                "runs `grok` (value not shown or read)."
            )

    if MODEL_LIST_ENV_VAR not in env:
        findings.append(_XAI_EXPLANATION)

    return findings


def diagnose(existing_text: str, document_text: str, path: str, environ=None) -> list[str]:
    """Report drift between the local config and the live gateway document."""
    live = parse_toml(document_text, "gateway document")
    local = parse_toml(existing_text, path)
    findings: list[str] = []

    live_endpoints = live.get("endpoints") or {}
    live_base = live_endpoints.get("models_base_url")

    endpoints = local.get("endpoints")
    if not isinstance(endpoints, dict) or not endpoints.get("models_base_url"):
        findings.append(
            "[endpoints] models_base_url is missing — run 'setup'. Without it Grok "
            "talks to xAI, not to this gateway."
        )
    else:
        base = endpoints["models_base_url"]
        if not isinstance(base, str) or not base.rstrip("/").endswith("/v1"):
            findings.append(
                f"[endpoints] models_base_url ('{base}') does not end in /v1, so "
                "Grok would fetch the wrong model list URL."
            )
        elif isinstance(live_base, str) and base.rstrip("/") != live_base.rstrip("/"):
            findings.append(
                f"[endpoints] models_base_url is '{base}'; this gateway reports "
                f"'{live_base}'."
            )

    live_models = _models_of(live)
    user_models = _models_of(local)

    findings += _diagnose_roles(local, live_models)

    for model_id in user_models:
        if model_id not in live_models:
            findings.append(
                f"model '{model_id}' is configured but not available upstream — "
                "calls to it would fail."
            )
    for model_id in live_models:
        if model_id not in user_models:
            findings.append(f"model '{model_id}' is available upstream but missing.")

    for model_id, live_model in live_models.items():
        current = user_models.get(model_id)
        if not isinstance(current, dict):
            continue

        backend = current.get("api_backend")
        if backend is not None and backend != EXPECTED_BACKEND:
            findings.append(
                f"model '{model_id}' api_backend is '{backend}'; this gateway serves "
                f"'{EXPECTED_BACKEND}'."
            )

        if "context_window" in live_model:
            if current.get("context_window") != live_model["context_window"]:
                findings.append(
                    f"model '{model_id}' context_window is "
                    f"{current.get('context_window', 'missing')}; live value is "
                    f"{live_model['context_window']}."
                )

        env_key = current.get("env_key")
        if env_key is None:
            findings.append(
                f"model '{model_id}' has no env_key — Grok would fall back to "
                "XAI_API_KEY or a login session."
            )
        elif isinstance(env_key, str) and not looks_like_env_name(env_key):
            findings.append(
                f"model '{model_id}' env_key looks like a literal secret rather than "
                "an environment-variable NAME (value not shown). Set it to e.g. "
                f"'{DEFAULT_ENV_KEY}'."
            )

        if "api_key" in current:
            findings.append(
                f"model '{model_id}' sets api_key inline (value not shown). Prefer "
                "env_key so no secret is stored on disk."
            )

    findings += diagnose_environment(local, environ)

    return findings


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="grok_build_config",
        description="Merge, check and refresh the Kiro gateway sections of a Grok "
                    "Build config file.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    def common(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--config", help=f"Grok config file (default {DEFAULT_CONFIG})")
        sp.add_argument("--url", help=f"Gateway base URL (default {DEFAULT_URL}, "
                                      "or $KIRO_GATEWAY_URL)")
        sp.add_argument("--api-key", help="Gateway proxy API key (or $KIRO_GATEWAY_KEY)")
        sp.add_argument("--base-url",
                        help="Override endpoints.models_base_url in the document")
        sp.add_argument("--env-key",
                        help=f"Name of the env var holding the gateway key "
                             f"(default {DEFAULT_ENV_KEY}); never a value")
        sp.add_argument("--timeout", type=float, default=30.0)

    for name, help_text in (
        ("setup", "merge the gateway sections into your Grok config"),
        ("doctor", "report drift between your config and the live catalog"),
        ("update", "refresh the managed model tables"),
    ):
        sp = sub.add_parser(name, help=help_text)
        common(sp)
        if name in ("setup", "update"):
            sp.add_argument("--write", action="store_true",
                            help="apply the change (default is a dry run)")
    return parser


def _fetch_for(args: argparse.Namespace) -> str:
    return fetch_document(
        url=args.url or os.environ.get("KIRO_GATEWAY_URL") or DEFAULT_URL,
        api_key=args.api_key or os.environ.get("KIRO_GATEWAY_KEY")
        or os.environ.get("PROXY_API_KEY"),
        base_url=args.base_url,
        env_key=args.env_key,
        timeout=args.timeout,
    )


def _apply(args: argparse.Namespace, merged: str, existing: str, path: str) -> int:
    if merged == existing:
        print(f"No changes needed in {path}.")
        return EXIT_OK

    print(render_diff(existing, merged, path))

    if not args.write:
        print("\nDry run — nothing written. Re-run with --write to apply.")
        return EXIT_DRIFT

    backup = write_text(path, merged)
    if backup:
        print(f"\nBackup: {backup}")
    print(f"Wrote {path}.")
    return EXIT_OK


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    path = config_path(args.config)

    try:
        existing = load_text(path)
        # Validate the user's file before touching it: an unparseable config is a
        # clean error, not a silent rewrite.
        parse_toml(existing, path)
        document = _fetch_for(args)

        if args.command == "doctor":
            findings = diagnose(existing, document, path)
            if not findings:
                print(f"{path} is up to date with the gateway catalog.")
                return EXIT_OK
            print(f"{len(findings)} issue(s) found in {path}:")
            for finding in findings:
                print(f"  - {finding}")
            return EXIT_DRIFT

        if args.command == "update" and not is_configured(existing):
            raise HelperError(
                "No [endpoints] models_base_url in this config yet — run 'setup' first."
            )

        merged = merge_document(existing, document)
        return _apply(args, merged, existing, path)

    except HelperError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_ERROR
    except OSError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return EXIT_ERROR


def is_configured(existing_text: str) -> bool:
    """True when our sections are already present (used to gate `update`)."""
    return any(is_owned(path) for path, _ in split_blocks(existing_text))


if __name__ == "__main__":
    sys.exit(main())
